import { Task } from "./page"
export const tasks : Task[] = [
  {
    id: "1",
    title: "Diseñar layout dashboard",
    description: "Crear sidebar y header responsive",
    completed: false,
    priority: "high",
    status: "todo",
    project: "App Tareas",
    tags: ["ui", "frontend"],
    dueDate: "2026-05-03",
    createdAt: "2026-05-01",
  },
  {
    id: "2",
    title: "Conectar Supabase",
    description: "Configurar auth y base de datos",
    completed: false,
    priority: "high",
    status: "in-progress",
    project: "Backend",
    tags: ["backend", "database"],
    dueDate: "2026-05-05",
    createdAt: "2026-05-01",
  },
  {
    id: "3",
    title: "Crear formulario nueva tarea",
    description: "Validación con React Hook Form",
    completed: true,
    priority: "medium",
    status: "done",
    project: "App Tareas",
    tags: ["forms"],
    dueDate: "2026-05-02",
    createdAt: "2026-04-30",
  },
  {
    id: "4",
    title: "Dark Mode",
    description: "Agregar cambio de tema con Zustand",
    completed: false,
    priority: "low",
    status: "todo",
    project: "UI",
    tags: ["theme"],
    dueDate: "2026-05-10",
    createdAt: "2026-05-01",
  },
  {
    id: "5",
    title: "Optimizar performance",
    description: "Memo + lazy loading",
    completed: false,
    priority: "medium",
    status: "todo",
    project: "Performance",
    tags: ["react"],
    dueDate: "2026-05-08",
    createdAt: "2026-05-02",
  },
];